### ISSUE TITLE
QA || [BLOCKER] API ERROR in FetchBill API

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/Dristi_kerala#702]
while trying to do payment in Pending task for summon, getting this API ERROR

URL : https://dristi-kerala-qa.pucar.org/billing-service/bill/v2/_fetchbill?tenantId=kl&businessService=task-summon&_=1724224798928

Response: {
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "BILL_GEN_MANDATORY_FIELDS_MISSING",
            "message": "Valid search criteria fields missing, please give some valid criteria like mobileNumber/email OR 'businessService & consumerCode' OR demandId",
            "description": null,
            "params": null
        }
    ]
}

CURL : `curl 'https://dristi-kerala-qa.pucar.org/billing-service/bill/v2/_fetchbill?tenantId=kl&businessService=task-summon&_=1724224798928' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.7' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/home/home-pending-task/post-payment-modal?filingNumber=F-C.1973.002-2024-000302&orderNumber=ORDER-NO-2024-08-21-000096' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Brave";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  --data-raw '{"RequestInfo":{"apiId":"Rainmaker","authToken":"14cc7c1d-4bbd-418c-bfd0-72208588e10a","userInfo":{"id":371,"uuid":"9a7e6e36-e233-4dfb-ba91-b59dd991dbab","userName":"7012345501","name":"Guru Lit","mobileNumber":"7012345501","emailId":null,"locale":null,"type":"CITIZEN","roles":[{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"DEPOSITION_VIEWER","code":"DEPOSITION_VIEWER","tenantId":"kl"},{"name":"Citizen","code":"CITIZEN","tenantId":"kl"},{"name":"APPLICATION_CREATOR","code":"APPLICATION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_DELETE","code":"SUBMISSION_DELETE","tenantId":"kl"},{"name":"DEPOSITION_CREATOR","code":"DEPOSITION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"SUBMISSION_CREATOR","code":"SUBMISSION_CREATOR","tenantId":"kl"},{"name":"APPLICATION_VIEWER","code":"APPLICATION_VIEWER","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"CASE_CREATOR","code":"CASE_CREATOR","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1724224798928|en_IN","plainAccessRequest":{}}}'`

![Image](https://github.com/user-attachments/assets/90b7235d-0821-4966-a9f3-209eff459698)

**Comment by prasanna2400** [comment]
payload is not correct as some fields are missing

**Comment by roopeshsagar** [comment]
https://dristi-kerala-qa.pucar.org/task/v1/search?_=1724229586285

{
    "ResponseInfo": {
        "apiId": "Rainmaker",
        "ver": null,
        "ts": null,
        "resMsgId": "uief87324",
        "msgId": "1724229586284|en_IN",
        "status": "successful"
    },
    "TotalCount": 0,
    "list": []
}

response for this api is coming as empty it should not come as empty because in the code  i filtered the necessary task from it 

here's the curl 
curl 'https://dristi-kerala-qa.pucar.org/task/v1/search?_=1724229586285' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.9,hi-IN;q=0.8,hi;q=0.7,en-IN;q=0.6,en-US;q=0.5' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/home/home-pending-task/post-payment-modal?filingNumber=F-C.1973.002-2024-000302&orderNumber=ORDER-NO-2024-08-21-000096' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  --data-raw '{"criteria":{"tenantId":"kl","filingNumber":"F-C.1973.002-2024-000302"},"RequestInfo":{"apiId":"Rainmaker","authToken":"0009b5b6-00c6-440d-a7c9-ee90b76bf819","userInfo":{"id":374,"uuid":"195dce0b-b74a-4ab3-a266-e042d8209e1c","userName":"7012345502","name":"B Guru Adv","mobileNumber":"7012345502","emailId":null,"locale":null,"type":"CITIZEN","roles":[{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"DEPOSITION_VIEWER","code":"DEPOSITION_VIEWER","tenantId":"kl"},{"name":"Citizen","code":"CITIZEN","tenantId":"kl"},{"name":"ADVOCATE_ROLE","code":"ADVOCATE_ROLE","tenantId":"kl"},{"name":"APPLICATION_CREATOR","code":"APPLICATION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_DELETE","code":"SUBMISSION_DELETE","tenantId":"kl"},{"name":"DEPOSITION_CREATOR","code":"DEPOSITION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"SUBMISSION_CREATOR","code":"SUBMISSION_CREATOR","tenantId":"kl"},{"name":"APPLICATION_VIEWER","code":"APPLICATION_VIEWER","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"CASE_CREATOR","code":"CASE_CREATOR","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1724229586284|en_IN","plainAccessRequest":{}}}'

**Comment by bhuvanyuguru** [comment]
resolved in QA
